USE [media]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_TVFeed_titleshort]    Script Date: 2020-09-03 16:35:47 ******/
CREATE NONCLUSTERED INDEX [IX_TVFeed_titleshort] ON [dbo].[TVFeed]
(
	[titleshort] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
